### ISSUE TITLE
How to add a server without shutting down the proxy server

### ISSUE THREAD

**Issue by jongilnose** [OpenSight/janus-cloud#25]
Hello
I have a question.
While running janus-cloud
I want to add one more janus server.
How to add a server without shutting down the proxy server
How should I implement it?

**Comment by jamken** [comment]
of course, no need to stop janus-proxy. I think you use the static janus server list feature which is in janus-proxy.yml. This feature is actually used to test the multi backend server feature of the proxy, so that it's not used in the real environment. Please use the janus-sentinel instead, which can supervise the status of janus process (restart it when crash) and  and report it to janus-proxy. Enjoy yourself.

**Comment by jongilnose** [comment]
Thank you for answer.
I have additional questions.
If you want to use janus-cloud in kubernetes.
Like you said. Do you also configure pods using docker (sentinel + janus server)?

**Comment by jamken** [comment]
No docker image by now, Thanks
